### ISSUE TITLE
[Suggestion Features] More Features

### ISSUE THREAD

**Issue by Gebardensprache** [Ecdcaeb/ResourceModLoader#1]
## About Config
Add new sub-folder to load to game config.  
Replace game config to RML Pack Config.

新增一个子文件夹，用于放置配置文件。
这个新config文件夹的优先度高于原config文件夹。
先读取原config后，再读取该config以达到替换效果。

**Comment by Ecdcaeb** [comment]
https://github.com/Ecdcaeb/ResourceModLoader/commit/1a21015eae56d14df2e9ea2544ade4c540175d06

**Comment by Ecdcaeb** [comment]
Read the document to know the changes.
阅读文档以知晓新变化。

**Comment by Ecdcaeb** [comment]
现在这个问题终于被解决了。
但是它不适用于Forge和FML的配置修改。
